# Generated by Django 4.2.7 on 2026-03-25 09:10

import apps.certificates.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Certificate Upload'), ('verify', 'Verification'), ('download', 'Download Result'), ('share', 'Share Result'), ('qr_access', 'QR Code Access'), ('bulk_upload', 'Bulk Upload'), ('admin_action', 'Admin Action')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('audit_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkVerificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to='bulk_jobs/input/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='bulk_jobs/output/')),
                ('total_certificates', models.PositiveIntegerField(default=0)),
                ('processed_certificates', models.PositiveIntegerField(default=0)),
                ('successful_verifications', models.PositiveIntegerField(default=0)),
                ('failed_verifications', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bulk_verification_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.certificates.models.certificate_upload_path)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_language', models.CharField(default='auto', max_length=10)),
                ('translate_enabled', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('tampered', 'Tampered'), ('unverified', 'Unverified')], max_length=20)),
                ('overall_confidence', models.FloatField()),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_fields', models.JSONField(default=dict)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('tamper_detected', models.BooleanField(default=False)),
                ('tamper_confidence', models.FloatField(blank=True, null=True)),
                ('tamper_issues', models.JSONField(default=list)),
                ('tamper_heatmap', models.ImageField(blank=True, null=True, upload_to=apps.certificates.models.result_upload_path)),
                ('database_match', models.BooleanField(default=False)),
                ('signature_valid', models.BooleanField(default=False)),
                ('signature_details', models.JSONField(default=dict)),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='certificates.certificate')),
                ('matched_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('matched_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutiondatabase')),
            ],
            options={
                'db_table': 'verification_results',
            },
        ),
    ]
