# Generated by Django 4.2.7 on 2026-03-25 14:39

import apps.certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.certificates.models.certificate_upload_path),
        ),
    ]
